version: '3.5'

services:

  db:
    container_name: container-database-quiz
    image: postgres:16
    restart: always
    env_file:
      - db.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/app/data
    networks:
      - quiz-network

  quiz-api:
    container_name: container-quiz-api
    depends_on:
      - db
    restart: always
    build:
      dockerfile: Dockerfile
    env_file:
      - dev.env
    ports:
      - "8080:8080"
    networks:
      - quiz-network

volumes:
  db_data: {}

networks:
  quiz-network:
    name: quiz-network
    driver: bridge