spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DEV_USER}
    url: jdbc:postgresql://${DEV_HOST}:5432/${DEV_DB}
    password: ${DEV_PASSWORD}
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      ddl-auto: update
cors:
  origins: ${CORS_ORIGINS}
