spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${PROD_USER}
    url: jdbc:postgresql://${PROD_HOST}:${PROD_PORT}/${PROD_DB}
    password: ${PROD_PASSWORD}
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      ddl-auto: update
cors:
  origins: ${CORS_ORIGINS}
