name: Build Docker Image And Push Docker Hub

on:
  push:
    branches: [main]

jobs:

  build-and-push:
    name: Build And Push Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Run tests
        run: mvn test

      - name: Build Project
        run: mvn package -DskipTests

      - name: Docker Login
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build Docker Image
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/quizapi .

      - name: Push Image Docker
        run: docker push ${{secrets.DOCKER_USERNAME}}/quizapi